# Generated by Django 4.2.7 on 2023-11-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reportcard", "0002_alter_student_options_alter_student_student_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportcard",
            name="date_of_report_card_generation",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name="reportcard",
            unique_together={("student_rank", "date_of_report_card_generation")},
        ),
    ]
